### ISSUE TITLE
Sending a msg on mobile (android) flaw

### ISSUE THREAD

**Issue by KodkodGates** [ykoblick/shabbatcom#10]
Many times, sending a msg does not work & not related to network issues.
Circle widget saying "Sending" does not send the message & just sits there.

This occurs on latest Android & previous versions as well.

**Comment by ykoblick** [comment]
It might very well be related to recipients settings where they are restricting messaging. Will check.

**Comment by ykoblick** [comment]
The post message api endpoint is now fully asynchronous, so the server response should be pretty snappy assuming the network is satisfactory. Still working on some of the screen jerkiness. Additionally anytime a member is blocking another (besides for when he/she is being blocked) the conversation does not display on the messaging view.
