### ISSUE TITLE
BUG with JQUERY Log on Edit post

### ISSUE THREAD

**Issue by KodkodGates** [ykoblick/shabbatcom#126]
BUG with JQUERY Log on Edit post

![edit post - shabbat](https://cloud.githubusercontent.com/assets/10193612/18527741/053058ee-7a94-11e6-97df-89a539bef320.JPG)

**Comment by KodkodGates** [comment]
![edit post - shabbat 2](https://cloud.githubusercontent.com/assets/10193612/18527869/81dbf966-7a94-11e6-9c70-85ce05557043.JPG)

**Comment by KodkodGates** [comment]
$Ajax call fails

//Load up the status update controls for edit
function LoadEditOverlay(sa_id) {

    console.log('load edit possibilities');

    clearStatusUpdateFields();

    //setTimeout(function () {
    //    //$('body')
    //    window.scrollTo({ top: '0px', left: '0px' }, 800, { easing: 'easeInBounce' });
    //}, 500);

    //console.log('got here');

    /* Local Variables */
    var $image = $('#image'),
        $thumbImage = $('#status-update-thumb-edit-image'),
        $controlsSection = $('#controls-section'),
        statusUpdateImage = null,
        $statusUpdateTextArea = $('#Update_Status_Box'),
        $statusUpdatePostButton = $('#status-update-post-button');


    //Must clear all the fields

    var profile_id = $('#ProfileId').val();
    var payload = {

        UserId: profile_id,
        Id: sa_id

    };

    var full_url = "/api/app/get-status-update";

    //Get the Status Update to poulate the fields
    //send a query to server side to present new content
    $.ajax({
        type: "POST",
        url: full_url,
        data: JSON.stringify(payload),
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        async: true,
        success: function (data) {

            x = data;
            //console.log(x);

            if (x.Doesnt_Exist == true) {
                var msg = "The status update could not be found";
                toastr.error('', msg);
                return;
            }

            if (x.Image_Edit_Raw != null) {
                if (x.Image_Edit_Raw.length > 0) {
                    //vm.imgInsertSrc = x.Image_Url;
                    //vm.saPictureActionText = "Remove Picture";
                    //vm.saActionClass = "red-text";


                    $thumbImage.attr('src', x.Image_Edit_Raw);
                    $image.attr('src', x.Image_Edit_Raw);

                    statusUpdateImage = x.Image_Edit_Raw;
                    statusUpdatePostData.Adding_New_Image = true;
                    statusUpdatePostData.Image = statusUpdateImage;

                    //Launch the cropping area and disguise the upload controls
                    $('#status-update-upload').fadeOut();
                    $('#status-update-image-edit-area').fadeIn();

                }
            }

            //vm.statusUpdateText = x.Text;
            //vm.saId = x.Id;

            //var templateUrl = 'templates/modals/status-update-modal.html';
            //$scope.showModalStatusUpdate(templateUrl);
            //$timeout(focusElm, 300);

            $statusUpdatePostButton.html('Update');
            $statusUpdateTextArea.val(x.Text);

            statusUpdatePostData.Id = sa_id;
            statusUpdatePostData.action = 'update';

            //setTimeout(function () {
            //    $statusUpdateTextArea.trigger('preview');
            //    $statusUpdatePostButton.html('Update');
            //}, 1000);

            //window.scrollTo(0, 0);


        }
    });




    return false;
}

**Comment by KodkodGates** [comment]
Debug window:

![edit post - shabbat 3](https://cloud.githubusercontent.com/assets/10193612/18530898/961c5abc-7aa1-11e6-9fc4-b33dd2cdcd49.JPG)

**Comment by ykoblick** [comment]
Merging this issue in to #issue 127 - initiative to streamline status update tooling across timeline, editing on feed is bug prone when editing pictures, and looking into reject and deprecate on status updates in this new version
