### ISSUE TITLE
Profile page rendering on mobile devices

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/shabbatcom#13]

**Comment by ykoblick** [comment]
Working on this in steps. Currently, the timeline view is displaying proper without the stickyness active. Will plan to review all the areas to address.

**Comment by ykoblick** [comment]
The action buttons should appear with concise text in their own row under the cover and profile images

**Comment by ykoblick** [comment]
Look additionally in the following areas:

- About Section
- Messaging modal -correspondence  images need to size down
- Friends section images size down
- Pictures section images size down
- REM Invite/Host me all messed up
