### ISSUE TITLE
Pictures in modal sometimes not resizing properly

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/shabbatcom#131]
Sometimes, when clicking on pics, they render very large, falling off the screen and making the "likes" and "comments" section disappear.

**Comment by ykoblick** [comment]
There are times when this is intended on old images that pre-date the ability to be liked and commented on - so that section is not supposed to display. I don;t know if thats the case here. A link or screenshot would help me instead of hunting.
