### ISSUE TITLE
No notifications showing on Web

### ISSUE THREAD

**Issue by KodkodGates** [ykoblick/shabbatcom#201]
Started today ~ See pics of error logs ~ Thx !!!

![shabbat dot com - notifications2 server errors on web](https://cloud.githubusercontent.com/assets/10193612/20980844/2a483b14-bc80-11e6-9f52-5e40faae78b6.JPG)
![shabbat dot com - notifications2 server errors on web 2](https://cloud.githubusercontent.com/assets/10193612/20980845/2a46cb08-bc80-11e6-8fa1-b4a74c5d023a.JPG)

**Comment by ykoblick** [comment]
Will check it today. Hmm not a helpful error message ☹

**Comment by KodkodGates** [comment]
That's all the console shows:

On your dev server, perhaps, change to unminimized angularjs & recheck 
all-notifications-v2

**Comment by KodkodGates** [comment]
Looks like it's been fixed. 👍
