### ISSUE TITLE
R'Juravel Recordings Stop Playing

### ISSUE THREAD

**Issue by Lainie6** [ykoblick/shabbatcom#256]
I used to listen to Rabbi Juravel on my other phone and when I used other apps, Rabbi Juravel would continue to play and I LOVED it.  Now it stops if I have to open any other app or click out of the Shabbat.com app.  I have an iPhone 5SE.  Is there a way to set it back the other way, so that it keeps playing even if I quickly check a text or something?  Thank you for making R'Juravel part of the app!!!

**Comment by ykoblick** [comment]
Thank you for posting.

I will look into this and figure out what ‘broke’ in the version you have.

If you don’t mind can you tell me the version of the App you have? On the main screen launch the left menu and see the version number next to the words ‘About Shabbat App’

Best,

Yehudah

**Comment by Lainie6** [comment]
1.13.7


Sent from my Mobile 

On Feb 20, 2017, at 8:25 PM, Yehudah Koblick <notifications@github.com> wrote:

Thank you for posting. 

I will look into this and figure out what ‘broke’ in the version you have. 

If you don’t mind can you tell me the version of the App you have? On the main screen launch the left menu and see the version number next to the words ‘About Shabbat App’ 

Best, 

Yehudah

**Comment by ykoblick** [comment]
And offhand do you know the version of Ios you have?

**Comment by Lainie6** [comment]
Does this help?


Sent from my Mobile 

On Feb 20, 2017, at 8:42 PM, Yehudah Koblick <notifications@github.com> wrote:

And offhand do you know the version of Ios you have?

**Comment by ykoblick** [comment]
Fixed for the next version (version 1.14.0). Submitting for review today and hopefully published by Monday

**Comment by Lainie6** [comment]
Yay!!!!  Thank you so much!  I will surely donate again. What a fantastic response and turnaround. 

Sent from my Mobile 

On Feb 23, 2017, at 10:43 AM, Yehudah Koblick <notifications@github.com> wrote:

Fixed for the next version (version 1.14.0). Submitting for review today and hopefully published by Monday
