### ISSUE TITLE
After adding a profile picture on the app, instead of taking you to the feed where you can see that your picture rendered...

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/shabbatcom#31]
It's give an option that says "add additional pictures". By taking you to the feed, you have to figure out to swipe right again and add more pictures.

**Comment by ykoblick** [comment]
Test Quality.

**Comment by ykoblick** [comment]
Ok, upon posting a picture - the app will navigate back to the 'add pictures' view to add more
