### ISSUE TITLE
When viewing someone's profile on the app, looking at their friends..

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/shabbatcom#32]
...and clicking "see all friends" you can add any of their friends. When clicking on the person with the person with the + icon, it should not take you to their profile each time you click it, but rather you should be able to go down the list and add friends.

**Comment by ykoblick** [comment]
Rov - when adding an issue - can you please state a general summary in the name and an elaboration in the description instead of making it a continuous post. It confuses me and is hard to refer to the issue by seeing the name when it just leads into the description.

**Comment by BenzionKlatzko** [comment]
sure

Warmly,

Benzion Klatzko


www.Shabbat.com <http://www.shabbat.com/> - build a kinder world
