### ISSUE TITLE
Status Update on website, when attaching a photo to a status with a website URL, ut shows the website preview and not the uploaded image.

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/shabbatcom#33]
<img width="733" alt="screen shot 2016-07-19 at 6 47 25 pm" src="https://cloud.githubusercontent.com/assets/20469449/16969251/77091eae-4de1-11e6-9a93-32898f584952.png">

This update ha a picture of a shabbat.com couple. It rendered on the app but not the website.

Basically, when uploading a pic, it should detect it and disable the website preview image automatically generated.

**Comment by ykoblick** [comment]
Not sure about this. See below - the item seems to be displaying as expected. Maybe I fixed it in the code and was pending publish. Your screenshot is the timeline and not the general feed as is mine. See below:

![image](https://cloud.githubusercontent.com/assets/1099389/17086021/5a42759a-51b5-11e6-9a68-bf76a9b6f8b5.png)

**Comment by BenzionKlatzko** [comment]
That image is only there because I took out the website preview image.. If
you go to my profile page you will see a post that I posted last night
about Havdalah.com. I attached a picture to it (that you can see on the
app). But on the website the image is not there, but rather the preview
from the website (that happens to be an image of my daughter and
son-in-law).

Warmly,

Benzion Klatzko


www.Shabbat.com <http://www.shabbat.com/> - build a kinder world

**Comment by ykoblick** [comment]
Got it, let me ask you this. If someone uploads a picture for a status update and the text he supplies references a website. Prob. we wouldn't want to output anything related to the website since it's the picture that is the focus. So, obviously the image to be shown will be rectified. But should I amend the logic this way as well?

**Comment by BenzionKlatzko** [comment]
Not sure what amending the logic means. The website should still render as
a link though.

Warmly,

Benzion Klatzko


www.Shabbat.com <http://www.shabbat.com/> - build a kinder world

**Comment by ykoblick** [comment]
I don’t think your understanding me – we’ll talk tomorrow.

**Comment by ykoblick** [comment]
Many key improvements here published last night and polished today.

* Line breaks visible on timeline feed status update items
* links 'discovered' and properly formatted
* If only a link is composed or is at the end of the text, the link title is not the actual href, it is instead the title of the url as returned by the embedly content provider.
* All web link images from embedly are ignored in the presence of an uploaded image.
* Wordpress referenced blank images are ignored from the display.
* Wrongly or partially typed url's are remedied in the formatting routine.
* Congruency between the app, home feed, and timeline adjusted and tested

**Comment by BenzionKlatzko** [comment]
Yasher koach!!
