### ISSUE TITLE
Clicking like does not show when the status was liked, but rather when the user signed up.

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/shabbatcom#37]
<img width="935" alt="screen shot 2016-07-21 at 9 19 53 am" src="https://cloud.githubusercontent.com/assets/20469449/17024260/4646b4c6-4f25-11e6-930d-484282f5b684.png">

**Comment by BenzionKlatzko** [comment]
Also, clicking like on a status on a persons profile page does not always translate into the like being rendered on the homepage. Meaning, I can click like on the status, then when I click home and find out status, that like is not there. This would compel me to click like again on the homepage for it to render. I see that because when are you click on the "who liked" on the homepage, my name is not there, even though I actually liked it on the person's profile page.

**Comment by ykoblick** [comment]
Translation:

Like display shows user signup date instead of liked date.

Fix like routine
