### ISSUE TITLE
Dating Profile - reference requirement?

### ISSUE THREAD

**Issue by ykoblick** [ykoblick/shabbatcom#47]
References are currently requires in the creation process on the site. Is this necessary?

![image](https://cloud.githubusercontent.com/assets/1099389/17160305/1d5164fc-5372-11e6-8b5d-766f79aadf4a.png)

**Comment by BenzionKlatzko** [comment]
Lets make it optional

Warmly,

Benzion Klatzko


<http://t.sidekickopen55.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRzNKgW3Ljs0K2BgXG0W2BFNn256dGkVf8cD4SP02?t=http%3A%2F%2Fwww.odyavo.org%2F&si=5893560192991232&pi=1ca55322-e5f3-44d3-c732-2cc202252fb1>



To Download the Shabbat.com app CLICK HERE (IPhone)
<http://t.sidekickopen55.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRzNKgW3Ljs0K2BgXG0W2BFNn256dGkVf8cD4SP02?t=https%3A%2F%2Fitunes.apple.com%2Fus%2Fapp%2Fshabbat%2Fid1037705799%3Fmt%3D8&si=5893560192991232&pi=1ca55322-e5f3-44d3-c732-2cc202252fb1>

To Download the Shabbat.com app CLICK HERE (Android)
<http://t.sidekickopen55.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRzNKgW3Ljs0K2BgXG0W2BFNn256dGkVf8cD4SP02?t=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.tribex.shabbat&si=5893560192991232&pi=1ca55322-e5f3-44d3-c732-2cc202252fb1>

**Comment by ykoblick** [comment]
Done (just so you know)
