### ISSUE TITLE
Clicking Camera/Upload on Status Update Post

### ISSUE THREAD

**Issue by BenzionKlatzko** [ykoblick/shabbatcom#56]
Clicking the Camera on the profile page when the picture is side ways wont rotate. (even after rotating it in the model)

It also takes a very long time to upload/render.

BTW, this is not an issue when uploading the "sideways" picture in the "Pictures" tab. It does work there. 

<img width="292" alt="screen shot 2016-07-31 at 2 02 09 pm" src="https://cloud.githubusercontent.com/assets/20469449/17278275/7493b8f6-5727-11e6-90c9-d69464b2770d.png">

**Comment by ykoblick** [comment]
This took some time to complete. It should be fixed as of my immediate publish.
