### ISSUE TITLE
Small bug: System generated new friends last night 

### ISSUE THREAD

**Issue by KodkodGates** [ykoblick/shabbatcom#63]
This was funny... & could be deleted.... I don't mind

Yaakov Jurkansky added you as a friend
Yesterday at 11:51 PM
 
Kassia Lana added you as a friend
Yesterday at 11:51 PM
 
Trevor Golden added you as a friend
Yesterday at 11:51 PM
 
Beyman Family added you as a friend
Yesterday at 11:51 PM
 
Meir Kolko added you as a friend
Yesterday at 11:51 PM
 
Joey Toledano added you as a friend
Yesterday at 11:51 PM
 
Daniel Nasimov added you as a friend
Yesterday at 11:51 PM
 
Avi Shimonov added you as a friend
Yesterday at 11:51 PM
 
Eddie Gadee added you as a friend
Yesterday at 11:51 PM
 
Diana Kakureb added you as a friend
Yesterday at 11:51 PM
 
Rose Khiz added you as a friend
Yesterday at 11:51 PM
 
Elaine Aminov added you as a friend
Yesterday at 11:51 PM
 
Simona Malakov added you as a friend
Yesterday at 11:51 PM
 
Shira Rivka added you as a friend
Yesterday at 11:51 PM
 
Yechiel Halbertal added you as a friend
Yesterday at 11:51 PM
 
Moshe Griner added you as a friend
Yesterday at 11:51 PM
 
Vered Musheyev added you as a friend
Yesterday at 11:51 PM
 
Mazal Akshlomo added you as a friend
Yesterday at 11:51 PM
 
Menucha Rabinowitz added you as a friend
Yesterday at 11:51 PM
 
Manny Zavulunov added you as a friend
Yesterday at 11:51 PM

**Comment by ykoblick** [comment]
This is intentional – based on a shared Shabbat experience.
