### ISSUE TITLE
Shabbat.com FAQ

### ISSUE THREAD

**Issue by ykoblick** [ykoblick/shabbatcom#84]
With copy to clipboard links

**Comment by KodkodGates** [comment]
FOR SURE ~ Every product comes with a user guide. 
Many non-tech users do not know how to use the web-site multiple features & apps.  
This could help a lot !!!

**Comment by ykoblick** [comment]
Ok - this initiative is launched. Ensure to provide to proposed questions in the repo. and implement into the faq page on the site.
