### ISSUE TITLE
UX Bugs on laptop

### ISSUE THREAD

**Issue by KodkodGates** [ykoblick/shabbatcom#90]
![yehuda](https://cloud.githubusercontent.com/assets/10193612/18016987/2f08ddea-6b9d-11e6-842b-4fce100b7504.JPG)

Settings page shows up underneath newsfeed on desktop.
Also, site seems to function quite slow since a few days ago on both mobile & desktop.

Running latest Chrome: 
1. Tried clearing all cookies & local storage from Shabbat.com does not fix this.
On Android also did the same.

Perhaps, my profile is actually corrupt on the site or code changes are at work affecting other users as well.

G'Shabbes !

**Comment by KodkodGates** [comment]
Another view ~ Double page rendering

![double pages rendering - shabbat](https://cloud.githubusercontent.com/assets/10193612/18037397/c8effccc-6d50-11e6-970d-441f9b3b4df2.JPG)

**Comment by ykoblick** [comment]
This is pretty strange. It looks like some Javascript may not be executing - can you check the console on the notifications page. In terms of the styling in the header - that's some css overrides or priority mismatch possibly. I'm not getting that in my testing on different form factors in chrome. Please check a gain and get back.

**Comment by KodkodGates** [comment]
Very strange indeed.

When I run it in latest chrome console enabled, no double rendering & notification as well as settings button works as should.  Once, I close the console, the UX render error comes back as before.

With console open
![shabbat com ux error 90](https://cloud.githubusercontent.com/assets/10193612/18188892/d0c204fa-7083-11e6-8ec6-f56778d31da7.JPG)

With console closed
![shabbat com ux error 90 - no console](https://cloud.githubusercontent.com/assets/10193612/18188912/fa230ba0-7083-11e6-8cb2-684b8c8d9348.JPG)

How strange is that ?!?!?!?

**Comment by KodkodGates** [comment]
Running latest Chrome Version 53.0.2785.89 m

I know what CSS override is & thought maybe it's a Chrome extension doing it.  Turned off Ad Block, yet don't think that's the issue cause it comes up fine with Console open.

What do you mean by "priority mismatch possibly" ~ So I can check for that later, perhaps ?

**Comment by KodkodGates** [comment]
Btw, did you try logging in as me, as I also can't edit my posts sometimes which is another open issue that came up when you suspected a corrupt profile which happened before because of chars in DB ?

**Comment by KodkodGates** [comment]
I think this could be the solution to this problem:

jquery-1.12.0.min.js:4 
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
unviewedContent.js:4 
getting unviewed alerts

![shabbat ux bugs](https://cloud.githubusercontent.com/assets/10193612/18211649/c5757828-710c-11e6-801d-46bda5a03d8d.JPG)

I noticed a few other issues with console open now always with regard to the new code base.
Presuming, Thurs & Friday there is a huge load also on servers which effect previous version of Angular.

G'Luck & Shabbat Shalom

**Comment by KodkodGates** [comment]
Fixed this morning !
